def  utf8_int_lookup( given_num_str ) :
         if given_num_str=='0':
                return int(given_num_str);
         elif given_num_str=='1':
                return int(given_num_str);
         elif given_num_str=='2':
                return int(given_num_str);
         elif given_num_str=='3':
                return int(given_num_str);
         elif given_num_str=='4':
                return int(given_num_str);
         elif given_num_str=='5':
                return int(given_num_str);
         elif given_num_str=='6':
                return int(given_num_str);
         elif given_num_str=='7':
                return int(given_num_str);
         elif given_num_str=='8':
                return int(given_num_str);
         elif given_num_str=='9':
                return int(given_num_str);
         elif given_num_str=='10':
                return int(given_num_str);
         elif given_num_str=='11':
                return int(given_num_str);
         elif given_num_str=='12':
                return int(given_num_str);
         elif given_num_str=='13':
                return int(given_num_str);
         elif given_num_str=='14':
                return int(given_num_str);
         elif given_num_str=='15':
                return int(given_num_str);
         elif given_num_str=='16':
                return int(given_num_str);
         elif given_num_str=='17':
                return int(given_num_str);
         elif given_num_str=='18':
                return int(given_num_str);
         elif given_num_str=='19':
                return int(given_num_str);
         elif given_num_str=='20':
                return int(given_num_str);
         elif given_num_str=='21':
                return int(given_num_str);
         elif given_num_str=='22':
                return int(given_num_str);
         elif given_num_str=='23':
                return int(given_num_str);
         elif given_num_str=='24':
                return int(given_num_str);
         elif given_num_str=='25':
                return int(given_num_str);
         elif given_num_str=='26':
                return int(given_num_str);
         elif given_num_str=='27':
                return int(given_num_str);
         elif given_num_str=='28':
                return int(given_num_str);
         elif given_num_str=='29':
                return int(given_num_str);
         elif given_num_str=='30':
                return int(given_num_str);
         elif given_num_str=='31':
                return int(given_num_str);
         elif given_num_str=='32':
                return int(given_num_str);
         elif given_num_str=='33':
                return int(given_num_str);
         elif given_num_str=='34':
                return int(given_num_str);
         elif given_num_str=='35':
                return int(given_num_str);
         elif given_num_str=='36':
                return int(given_num_str);
         elif given_num_str=='37':
                return int(given_num_str);
         elif given_num_str=='38':
                return int(given_num_str);
         elif given_num_str=='39':
                return int(given_num_str);
         elif given_num_str=='40':
                return int(given_num_str);
         elif given_num_str=='41':
                return int(given_num_str);
         elif given_num_str=='42':
                return int(given_num_str);
         elif given_num_str=='43':
                return int(given_num_str);
         elif given_num_str=='44':
                return int(given_num_str);
         elif given_num_str=='45':
                return int(given_num_str);
         elif given_num_str=='46':
                return int(given_num_str);
         elif given_num_str=='47':
                return int(given_num_str);
         elif given_num_str=='48':
                return int(given_num_str);
         elif given_num_str=='49':
                return int(given_num_str);
         elif given_num_str=='50':
                return int(given_num_str);
         elif given_num_str=='51':
                return int(given_num_str);
         elif given_num_str=='52':
                return int(given_num_str);
         elif given_num_str=='53':
                return int(given_num_str);
         elif given_num_str=='54':
                return int(given_num_str);
         elif given_num_str=='55':
                return int(given_num_str);
         elif given_num_str=='56':
                return int(given_num_str);
         elif given_num_str=='57':
                return int(given_num_str);
         elif given_num_str=='58':
                return int(given_num_str);
         elif given_num_str=='59':
                return int(given_num_str);
         elif given_num_str=='60':
                return int(given_num_str);
         elif given_num_str=='61':
                return int(given_num_str);
         elif given_num_str=='62':
                return int(given_num_str);
         elif given_num_str=='63':
                return int(given_num_str);
         elif given_num_str=='64':
                return int(given_num_str);
         elif given_num_str=='65':
                return int(given_num_str);
         elif given_num_str=='66':
                return int(given_num_str);
         elif given_num_str=='67':
                return int(given_num_str);
         elif given_num_str=='68':
                return int(given_num_str);
         elif given_num_str=='69':
                return int(given_num_str);
         elif given_num_str=='70':
                return int(given_num_str);
         elif given_num_str=='71':
                return int(given_num_str);
         elif given_num_str=='72':
                return int(given_num_str);
         elif given_num_str=='73':
                return int(given_num_str);
         elif given_num_str=='74':
                return int(given_num_str);
         elif given_num_str=='75':
                return int(given_num_str);
         elif given_num_str=='76':
                return int(given_num_str);
         elif given_num_str=='77':
                return int(given_num_str);
         elif given_num_str=='78':
                return int(given_num_str);
         elif given_num_str=='79':
                return int(given_num_str);
         elif given_num_str=='80':
                return int(given_num_str);
         elif given_num_str=='81':
                return int(given_num_str);
         elif given_num_str=='82':
                return int(given_num_str);
         elif given_num_str=='83':
                return int(given_num_str);
         elif given_num_str=='84':
                return int(given_num_str);
         elif given_num_str=='85':
                return int(given_num_str);
         elif given_num_str=='86':
                return int(given_num_str);
         elif given_num_str=='87':
                return int(given_num_str);
         elif given_num_str=='88':
                return int(given_num_str);
         elif given_num_str=='89':
                return int(given_num_str);
         elif given_num_str=='90':
                return int(given_num_str);
         elif given_num_str=='91':
                return int(given_num_str);
         elif given_num_str=='92':
                return int(given_num_str);
         elif given_num_str=='93':
                return int(given_num_str);
         elif given_num_str=='94':
                return int(given_num_str);
         elif given_num_str=='95':
                return int(given_num_str);
         elif given_num_str=='96':
                return int(given_num_str);
         elif given_num_str=='97':
                return int(given_num_str);
         elif given_num_str=='98':
                return int(given_num_str);
         elif given_num_str=='99':
                return int(given_num_str);
         elif given_num_str=='100':
                return int(given_num_str);
         elif given_num_str=='101':
                return int(given_num_str);
         elif given_num_str=='102':
                return int(given_num_str);
         elif given_num_str=='103':
                return int(given_num_str);
         elif given_num_str=='104':
                return int(given_num_str);
         elif given_num_str=='105':
                return int(given_num_str);
         elif given_num_str=='106':
                return int(given_num_str);
         elif given_num_str=='107':
                return int(given_num_str);
         elif given_num_str=='108':
                return int(given_num_str);
         elif given_num_str=='109':
                return int(given_num_str);
         elif given_num_str=='110':
                return int(given_num_str);
         elif given_num_str=='111':
                return int(given_num_str);
         elif given_num_str=='112':
                return int(given_num_str);
         elif given_num_str=='113':
                return int(given_num_str);
         elif given_num_str=='114':
                return int(given_num_str);
         elif given_num_str=='115':
                return int(given_num_str);
         elif given_num_str=='116':
                return int(given_num_str);
         elif given_num_str=='117':
                return int(given_num_str);
         elif given_num_str=='118':
                return int(given_num_str);
         elif given_num_str=='119':
                return int(given_num_str);
         elif given_num_str=='120':
                return int(given_num_str);
         elif given_num_str=='121':
                return int(given_num_str);
         elif given_num_str=='122':
                return int(given_num_str);
         elif given_num_str=='123':
                return int(given_num_str);
         elif given_num_str=='124':
                return int(given_num_str);
         elif given_num_str=='125':
                return int(given_num_str);
         elif given_num_str=='126':
                return int(given_num_str);
	 elif given_num_str=='126':
                return int(given_num_str);


	 else :
		return "" ; 
